name: "Amazon-ecs-task-definition-dynamic-fields"
description: "Dynamically update any task definition field"
author: "Oswald Gyabaah"
inputs:
  task-family:
    description: "Name of the task definition family"
    required: true
  task-revision:
    description: "Revision of the task definition family"
    default: ""
    required: false
  aws-access-key-id:
    description: "Your AWS access key ID: pass through github secrets"
    required: true
  aws-secret-access-key:
    description: "Your AWS secret access key: pass through github secrets"
    required: true
  aws-region:
    description: "The region of your ecs cluster"
    required: true
  image-uri:
    description: "The URI of the new image"
    required: true
  cluster-name:
    description: "The name of the cluster to run the service on"
    required: true
  service-name:
    description: "The name of the service name of the service to update"
    required: true
outputs:
  task-definition:
    description: "A new task definition with your changes"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.family-name }}
branding: #generates a logo for our action
  icon: arrow-down #icon of the image
  color: blue # background color of the logo of our action
