name: Testing action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-hello-world:
    name: Test hello world
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test hello world
        uses: ./
        id: hello
        with:
          family-name: "Testing Family Name"
      - name: Echo output
        run: echo "${{ steps.hello.outputs.task-definition }}"
