name: Testing action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-hello-world:
    name: Test hello world
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test hello world
        uses: ./
        id: hello
        with:
          task-family: "file-service-task"
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Echo output
        run: echo ${{ steps.hello.outputs.task-definition }}
